name: Drizzle DB Push

on:
  pull_request:
    types: [closed]
    branches: [main]

jobs:
  push-db:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup pnpm (uses version from package.json's packageManager)
        uses: pnpm/action-setup@v4
        with:
          run_install: false

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Push database schema (Drizzle)
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
        run: pnpm db:push
